
name: Release

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: Check out

    - name: Check DNS
      run: | 
        nslookup repo.maven.apache.org

    - name: Get Maven project version
      run: |
        echo "project_version=$(mvn -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive org.codehaus.mojo:exec-maven-plugin:3.1.0:exec  --file pom.xml)" >> $GITHUB_ENV
        cat $GITHUB_ENV

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven (Java 8)
      run: mvn -B package --file pom.xml

    - name: List target directory
      run: ls -l target

    - name: Copy dist artifacts to staging directory
      run: mkdir staging && cp target/*with-dependencies.jar staging/codeforiserver-${{ env.project_version }}.jar

    - name: Create the tag and release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ env.project_version }}
        name: v${{ env.project_version }}
        files: staging/codeforiserver-${{ env.project_version }}.jar
