
name: Release

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: Check out

    - name: Override DNS for Sonatype repo
      run: |
        mkdir -p ~/.m2/
        touch ~/.m2/settings.xml 
        echo " <settings> <mirrors> <mirror> <id>centralhttps</id> <mirrorOf>central</mirrorOf> <name>Maven central https</name> <url>https://repo1.maven.org/maven2/</url> </mirror> </mirrors></settings>" >> ~/.m2/settings.xml 

    - name: Get Maven project version
      run: |
        echo "project_version=$(mvn -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive org.codehaus.mojo:exec-maven-plugin:3.1.0:exec  --file pom.xml)" >> $GITHUB_ENV
        cat $GITHUB_ENV

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven (Java 8)
      run: mvn -B package --file pom.xml

    - name: List target directory
      run: ls -l target

    - name: Copy dist artifacts to staging directory
      run: mkdir staging && cp target/*with-dependencies.jar staging/mapepire-server-${{ env.project_version }}.jar

    - name: Create the tag and release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ env.project_version }}
        name: v${{ env.project_version }}
        files: staging/codeforiserver-${{ env.project_version }}.jar
