
name: Release

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    environment: OSSBUILD

    steps:
    - uses: actions/checkout@v3
      name: Check out

    - name: Override DNS for Sonatype repo
      run: |
        mkdir -p ~/.m2/
        touch ~/.m2/settings.xml 
        echo " <settings> <mirrors> <mirror> <id>centralhttps</id> <mirrorOf>central</mirrorOf> <name>Maven central https</name> <url>https://repo1.maven.org/maven2/</url> </mirror> </mirrors></settings>" >> ~/.m2/settings.xml 

    - name: Get Maven project version
      run: |
        echo "project_version=$(mvn -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive org.codehaus.mojo:exec-maven-plugin:3.1.0:exec  --file pom.xml)" >> $GITHUB_ENV
        cat $GITHUB_ENV

    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven (Java 8)
      run: mvn -B package --file pom.xml

    - name: List target directory
      run: ls -l target

    - name: Create jt400 pseudo-directory
      run: sudo mkdir -p /QIBM/ProdData/OS400/jt400/lib/

    - name: Change ownership of jt400 psudo-directory
      run: sudo chown $USER /QIBM/ProdData/OS400/jt400/lib/

    - name: Fetch jt400.jar
      run: sudo curl https://repo1.maven.org/maven2/net/sf/jt400/jt400/10.7/jt400-10.7.jar -o /QIBM/ProdData/OS400/jt400/lib/jt400.jar

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Create staging directory
      run: |
        mkdir -p staging/opt/mapepire/lib/mapepire/
        mkdir -p staging/opt/mapepire/bin/

    - name: Populate staging directory
      run: |
        mv scripts/mapepire-start.sh staging/opt/mapepire/bin/mapepire
        mv target/mapepire-server-${{ env.project_version }}-jar-with-dependencies.jar staging/opt/mapepire/lib/mapepire/mapepire-server.jar
        mv LICENSE staging/opt/mapepire/lib/mapepire/LICENSE
        mv service-commander-def.yaml staging/opt/mapepire/lib/mapepire/mapepire.yaml

    - name: Create distribution .zip and move JAR file
      run: |
        pushd staging/opt/mapepire
        zip -r ../../../mapepire-server-${{ env.project_version }}.zip bin lib
        mv lib/mapepire/mapepire-server.jar ../../../mapepire-server.jar
        popd

    - name: Create the tag and release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ env.project_version }}
        name: v${{ env.project_version }}
        files: |
          mapepire-server-${{ env.project_version }}.zip
          mapepire-server.jar

    - name: Install NPM Dependencies
      run: npm i -g @ibm/ibmi-ci

    - name: Deploy Server to IBM i
      run: | 
        ici \
          --rcwd "/home/${{ secrets.IBMI_USER }}" \
          --cmd "mkdir -p /opt/download/release" \
          --rcwd "/opt/download/release" \
          --cmd "rm -f mapepire-server-${{ env.project_version }}.zip" \
          --cmd "wget -O mapepire-server-${{ env.project_version }}.zip https://github.com/Mapepire-IBMi/mapepire-server/releases/latest/download/mapepire-server-${{ env.project_version }}.zip" \
          --cmd "mkdir -p /opt/mapepire/release" \
          --rcwd "/opt/mapepire/release" \
          --cmd "rm -fr bin lib" \
          --cmd "jar xvf /opt/download/release/mapepire-server-${{ env.project_version }}.zip" \
          --cmd "chown -R qsys ." \
          --cmd "rm -fr /QOpenSys/etc/sc/services/mapepire.yaml" \
          --cmd "ln -sf /opt/mapepire/release/lib/mapepire/mapepire.yaml /QOpenSys/etc/sc/services/mapepire.yaml" \
          --cmd "mkdir -p /QOpenSys/etc/mapepire" \
          --cmd "touch /QOpenSys/etc/mapepire/iprules.conf" \
          --cmd "touch /QOpenSys/etc/mapepire/iprules-single.conf" \
          --cmd "sc -v check mapepire" \
          --cmd "sc -v stop mapepire" \
          --cmd "sc -v start mapepire" \
      env:
        IBMI_HOST: ${{ secrets.IBMI_HOST }}
        IBMI_USER: ${{ secrets.IBMI_USER }}
        IBMI_PASSWORD: ${{ secrets.IBMI_PASSWORD }}
        IBMI_SSH_PORT: ${{ secrets.IBMI_SSH_PORT }}
