# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: create jt400 psudo-directory
      run: sudo mkdir -p /QIBM/ProdData/OS400/jt400/lib/
    - name: change ownership of jt400 psudo-directory
      run: sudo chown $USER /QIBM/ProdData/OS400/jt400/lib/
    - name: fetch jt400.jar
      run: sudo curl https://repo1.maven.org/maven2/net/sf/jt400/jt400/10.7/jt400-10.7.jar -o /QIBM/ProdData/OS400/jt400/lib/jt400.jar
    - name: Build with Maven
      run: mvn -B package --file pom.xml
